import "./globals.css";
import SideNav from "./ui/sideNav/SideNav";

export const metadata = {
  title: "Trading App Dashboard",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`body`}>
        <SideNav />
        {children}
      </body>
    </html>
  );
}
